version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      shell: cmd.exe
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run:
          name: "compilar example"
          shell: cmd.exe
          command: |
              cd example
              copy *.cfg .\example\bin\*.*
              ..\cmp\dcc32 project1>log.txt
              copy *.txt .\example\bin\*.*

      - store_artifacts:
          path: ./example/bin
          destination: artifact-file 